# Generated by Django 3.1.6 on 2021-02-16 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='id',
        ),
        migrations.AddField(
            model_name='usermessage',
            name='object_id',
            field=models.CharField(default=',', max_length=50, primary_key=True, serialize=False, verbose_name='主键'),
        ),
    ]
